repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        types: [python]
        entry: pipenv run black


      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py,third_parties

      # - id: mypy
      #   name: mypy
      #   stages: [commit]
      #   language: system
      #   entry: pipenv run mypy src
      #   types: [python]
      #   pass_filenames: false